#!/usr/bin/env bash

set -eux

EXERCISE=${1?"EXERCISE arg is required, e.g. 1.13"}
SCRIPT_PATH=$(cd "$(dirname "$0")"; pwd -P)
EXERCISE_DIR="$SCRIPT_PATH/../exercises/$EXERCISE"

mkdir -p $EXERCISE_DIR

for ext in '.js' '.spec.js'; do
    touch ${EXERCISE_DIR}/${EXERCISE}${ext}
done

